// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestaurantApp.Models
{
    public partial class Menu
    {
        public Menu()
        {
            OrderItems = new HashSet<OrderItems>();
        }

        public int MenuId { get; set; }
        public int? ResId { get; set; }
        public string Cuisine { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public int? Price { get; set; }
        public string Description { get; set; }
        public bool? IsAvailable { get; set; }

        public virtual ResUser Res { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}