// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestaurantApp.Models
{
    public partial class ResEmployee
    {
        public ResEmployee()
        {
            ResOrder = new HashSet<ResOrder>();
        }

        public int EmpId { get; set; }
        public int? ResId { get; set; }
        public string Name { get; set; }
        public DateTime? Dob { get; set; }
        public bool? Gender { get; set; }
        public string PhoneNo { get; set; }
        public string Category { get; set; }

        public virtual ResUser Res { get; set; }
        public virtual ICollection<ResOrder> ResOrder { get; set; }
    }
}