// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestaurantApp.Models
{
    public partial class ResOrder
    {
        public ResOrder()
        {
            OrderItems = new HashSet<OrderItems>();
        }

        public int OrderId { get; set; }
        public int? ResId { get; set; }
        public int? OwnerId { get; set; }
        public int? TableId { get; set; }
        public bool? IsCompleted { get; set; }

        public virtual ResEmployee Owner { get; set; }
        public virtual ResUser Res { get; set; }
        public virtual ResTable Table { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}