// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestaurantApp.Models
{
    public partial class ResTable
    {
        public ResTable()
        {
            ResOrder = new HashSet<ResOrder>();
        }

        public int TableId { get; set; }
        public int? ResId { get; set; }
        public string Name { get; set; }
        public int? Capacity { get; set; }
        public bool? IsAvailable { get; set; }

        public virtual ResUser Res { get; set; }
        public virtual ICollection<ResOrder> ResOrder { get; set; }
    }
}