// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestaurantApp.Models
{
    public partial class ResUser
    {
        public ResUser()
        {
            Menu = new HashSet<Menu>();
            ResEmployee = new HashSet<ResEmployee>();
            ResOrder = new HashSet<ResOrder>();
            ResTable = new HashSet<ResTable>();
        }

        public int ResId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Location { get; set; }
        public string PhoneNo { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }

        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<ResEmployee> ResEmployee { get; set; }
        public virtual ICollection<ResOrder> ResOrder { get; set; }
        public virtual ICollection<ResTable> ResTable { get; set; }
    }
}